Repository Devminjeong-eum/frontend, pull requests merged in 2024-04, with the labels that each got.

#4 feat: React-Query Provider 세팅 및 Detail 페이지 Prefetch
  src/app/words/[word-id]/page.tsx
  src/app/words/[wordId]/loading.tsx
  src/app/words/[wordId]/page.tsx
  src/components/common/BackButton.tsx
  src/components/pages/detail/index.tsx
  src/components/pages/home/index.tsx
  src/components/pages/search/index.tsx
  src/hooks/query/useWordDetail.ts
  src/providers/QueryProvider.tsx
Labels: ✨ feat

#5 fix: home type error
  src/app/home/page.tsx
  src/components/layout/Header.tsx
  src/components/pages/home/HomeItem.tsx
  src/components/pages/home/Pagination.tsx
  src/components/pages/home/index.tsx
  src/constants/queryKey.ts
  src/hooks/query/usePosts.ts
  src/routes/path.ts
  src/types/main.ts
  tsconfig.json
Labels: ♻️ refactor

#7 style: 피그마 기준 Home 관련 컴포넌트 스타일 1차 수정
  src/app/home/page.tsx
  src/app/not-found.tsx
  src/components/common/ErrorHandlingMarkup.tsx
  src/components/layout/Header.tsx
  src/components/pages/home/HomeItem.tsx
  src/components/pages/home/HomeTrending.tsx
  src/components/pages/home/Pagination.tsx
  src/components/pages/home/index.tsx
  src/components/pages/not-found/index.tsx
  src/components/svg-component/CrownSvg.tsx
  src/components/svg-component/HeartSvg.tsx
  src/components/svg-component/TriangleSvg.tsx
  src/hooks/query/usePosts.ts
  src/types/main.ts
Labels: ✍️ UI
