Repository Devminjeong-eum/frontend, pull requests merged in 2024-04, with the labels that each got.

#1 feat: 메인페이지 기능 구현 (제외: 페이지네이션 컴포넌트)
  package-lock.json
  package.json
  src/Layout/Header.tsx
  src/Layout/SearchBar.tsx
  src/Layout/index.tsx
  src/assets/react.svg
  src/components/common/CustomButton.tsx
  src/components/common/Modal.tsx
  src/components/svgComponent/LogoSvg.tsx
  src/components/svgComponent/MagnifierSvg.tsx
  src/components/svgComponent/MenuSvg.tsx
  src/components/svgComponent/SpeakerSvg.tsx
  src/hooks/useScroll.tsx
  src/pages/Main/MainItem.tsx
  src/pages/Main/index.tsx
  src/routes/index.tsx
  tailwind.config.js
  tsconfig.json
  vite.config.ts
Labels: 기능 추가, 설정, 스타일 (마크업)

#3 feat: pagination 구현
  src/Layout/Header.tsx
  src/Layout/SearchBar.tsx
  src/components/common/CustomButton.tsx
  src/components/main/Pagination.tsx
  src/components/svgComponent/OneButtonSvg.tsx
  src/components/svgComponent/TwoButtonSvg.tsx
  src/hooks/usePagination.tsx
  src/index.css
  src/pages/Main/index.tsx
  src/routes/index.tsx
Labels: 기능 추가, 스타일 (마크업)

#4 feat: error handling page markup
  src/components/common/ErrorHandlingMarkup.tsx
  src/components/svgComponent/ErrorSvg.tsx
  src/components/svgComponent/LockSvg.tsx
  src/components/svgComponent/OneButtonSvg.tsx
  src/components/svgComponent/TwoButtonSvg.tsx
  src/index.css
  src/layout/Footer.tsx
  src/layout/Header.tsx
  src/layout/LayoutWrapper.tsx
  src/layout/SearchBar.tsx
  src/layout/index.tsx
  src/pages/Error/index.tsx
  src/pages/SystemCheckNotice/index.tsx
  src/routes/index.tsx
Labels: 기능 추가, 스타일 (마크업)

#6 feat: 디테일 페이지 마크업 및 레이아웃 구성 변경
  src/components/common/BackButton.tsx
  src/components/svgComponent/BackButtonSvg.tsx
  src/components/svgComponent/CorrectSvg.tsx
  src/components/svgComponent/ExternalSvg.tsx
  src/components/svgComponent/WrongSvg.tsx
  src/layout/Layout.tsx
  src/pages/Detail/index.tsx
  src/routes/index.tsx
  tailwind.config.js
Labels: 기능 추가, 스타일 (마크업)

#7 feat: 로딩 스피너 추가 및 메인 페이지 타입 수정
  .gitignore
  src/api/axios.ts
  src/api/main.ts
  src/components/common/ErrorHandlingMarkup.tsx
  src/components/common/Modal.tsx
  src/components/common/Spinner.tsx
  src/components/common/ToolTip.tsx
  src/components/main/Pagination.tsx
  src/components/main/QuizButton.tsx
  src/components/svgComponent/LogoColorSvg.tsx
  src/components/svgComponent/OneButtonSvg.tsx
  src/hooks/query/usePosts.ts
  src/hooks/usePagination.tsx
  src/index.css
  src/layout/Footer.tsx
  src/layout/Header.tsx
  src/pages/Error/index.tsx
  src/pages/Main/MainItem.tsx
  src/pages/Main/index.tsx
  src/types/errorHandling.ts
  src/types/main.ts
Labels: 수정 (리팩토링), 스타일 (마크업)

#11 fix: build error 해결
  src/components/main/Pagination.tsx
  src/hooks/usePagination.tsx
Labels: 버그

#8 feat: 에러 페이지 추가
  src/components/common/ErrorHandlingMarkup.tsx
  src/components/svgComponent/NotFoundSvg.tsx
  src/pages/NotFound/NotFound.tsx
  src/routes/index.tsx
Labels: 기능 추가, 스타일 (마크업)

#17 feat: wordExamples -> wordExample 변수명 변경
  src/pages/Detail/index.tsx
  src/types/main.ts
Labels: 버그, 수정 (리팩토링)
