Repository Devminjeong-eum/frontend, pull requests merged in 2024-05, with the labels that each got.

#10 fix: build error 나는 부분(SearchItem) 주석 처리 후 빌드 확인
  src/components/pages/search/index.tsx
Labels: 🐛 bug

#12 feat: 단어장 페이지 마크업
  src/app/my-wordbook/page.tsx
  src/components/common/Pagination.tsx
  src/components/common/WordItem.tsx
  src/components/pages/home/index.tsx
  src/components/pages/my-wordbook/MyWordbookHeader.tsx
  src/components/pages/my-wordbook/QuizBanner.tsx
  src/components/pages/my-wordbook/index.tsx
  src/components/svg-component/NoWordSvg.tsx
  src/types/main.ts
  tailwind.config.js
Labels: ✨ feat

#13 style: 메인페이지 스타일링
  .eslintrc.cjs
  package-lock.json
  package.json
  src/app/home/page.tsx
  src/app/layout.tsx
  src/components/common/Modal.tsx
  src/components/common/WordItem.tsx
  src/components/layout/Header.tsx
  src/components/layout/SearchBar.tsx
  src/components/pages/detail/DetailLoading.tsx
  src/components/pages/detail/index.tsx
  src/components/pages/home/HomeToggleZone.tsx
  src/components/pages/home/HomeTrending.tsx
  src/components/pages/home/index.tsx
  src/components/pages/quiz/index.tsx
  src/components/svg-component/CrownLinearSvg.tsx
  src/components/svg-component/FillArrowSvg.tsx
  src/components/svg-component/HeartSvg.tsx
  tailwind.config.js
Labels: ♻️ refactor, ✍️ UI

#14 feat: 잘못된 정보 문의 버튼 추가
  src/components/pages/detail/ReportButton.tsx
  src/components/pages/detail/index.tsx
  src/components/svg-component/NoticeIconSvg.tsx
  src/components/svg-component/RightArrowSvg.tsx
Labels: ✨ feat, ✍️ UI

#15 fix: 잘못된 fetch type 수정
  src/fetcher/fetch.ts
Labels: 🐛 bug

#16 feat: 단어장 페이지에서 dropdown 메뉴 추가
  src/app/my-wordbook/page.tsx
  src/app/user/wordbook/page.tsx
  src/components/layout/Header.tsx
  src/components/pages/quiz/index.tsx
  src/components/pages/wordbook/QuizBanner.tsx
  src/components/pages/wordbook/WordbookDropdown.tsx
  src/components/pages/wordbook/WordbookHeader.tsx
  src/components/pages/wordbook/index.tsx
  src/components/svg-component/ArrowDownSvg.tsx
  src/routes/path.ts
Labels: ✨ feat

#19 [DEV-23] 단어 디테일 페이지 API 적용
  src/app/words/[wordId]/page.tsx
  src/components/pages/detail/DetailLoading.tsx
  src/components/pages/detail/index.tsx
  src/fetcher/index.ts
  src/fetcher/types.ts
  src/types/main.ts
Labels: ✨ feat

#21 hotfix: 불필요한 파일 때문에 나는 빌드 에러 파일 삭제로 수정
  src/hooks/query/useWordDetail.ts
Labels: 🐛 bug

#17 feat: 카카오 로그인 api 연동
  src/app/api/auth/kakao/redirect/route.ts
  src/app/api/auth/kakao/route.ts
  src/components/pages/login/index.tsx
  src/fetcher/index.ts
Labels: ✨ feat

#22 hotfix: 제거된 await 다시 생성
  src/fetcher/index.ts
  src/fetcher/instance.ts
Labels: 🐛 bug

#18 feat: 검색 기능 추가
  src/app/search/page.tsx
  src/app/word/search/page.tsx
  src/components/common/ToolTip.tsx
  src/components/layout/Header.tsx
  src/components/layout/SearchBar.tsx
  src/components/pages/search/NotFoundWord.tsx
  src/components/pages/search/SearchItem.tsx
  src/components/pages/search/index.tsx
  src/components/svg-component/ClearSearchBarSvg.tsx
  src/constants/queryKey.ts
  src/fetcher/index.ts
  src/fetcher/types.ts
Labels: ✨ feat

#20 [DEV-36] 카카오 공유하기 기능 구현
  src/app/layout.tsx
  src/components/pages/quiz/QuizResult.tsx
  src/hooks/useLoadKakaoScript.ts
Labels: ✨ feat

#23 hotfix: 로그인 페이지, 디테일 페이지 에러 수정
  src/app/words/[wordId]/page.tsx
  src/components/pages/login/index.tsx
  src/fetcher/types.ts
Labels: 🐛 bug

#24 [DEV-45] 검색 기능 실시간으로 검색되도록 수정
  src/app/word/search/page.tsx
  src/components/layout/SearchBar.tsx
  src/components/pages/search/NotFoundWord.tsx
  src/components/pages/search/SearchItem.tsx
  src/hooks/useDebounce.ts
  tailwind.config.js
Labels: ✨ feat
