Repository Devminjeong-eum/frontend, pull requests merged in 2024-06, with the labels that each got.

#26 [DEV-10] feat: 메인 페이지 단어 API 적용 및 레이아웃 수정
  src/app/home/page.tsx
  src/components/common/WordItem.tsx
  src/components/layout/SearchBar.tsx
  src/components/pages/home/HomeToggleZone.tsx
  src/components/pages/home/HomeTrending.tsx
  src/components/pages/home/all-posts/index.tsx
  src/components/pages/home/index.tsx
  src/components/pages/home/trending-posts/GeneralRanking.tsx
  src/components/pages/home/trending-posts/TopRanking.tsx
  src/components/pages/home/trending-posts/TrendingDescription.tsx
  src/components/pages/home/trending-posts/index.tsx
  src/fetcher/index.ts
  src/hooks/query/useGetAllPosts.ts
  src/hooks/query/usePosts.ts
  src/types/main.ts
Labels: ✨ feat

#27 [DEV-43] feat: 단어장 페이지에 좋아요 목록 API 적용
  src/app/user/wordbook/page.tsx
  src/components/pages/wordbook/index.tsx
  src/constants/queryKey.ts
  src/fetcher/index.ts
  src/fetcher/types.ts
  src/hooks/query/useGetLikedWord.ts
Labels: ✨ feat

#30 [FE] 트렌딩 단어 오픈 예정 UI 구현
  src/components/pages/home/HomeToggleZone.tsx
  src/components/pages/home/all-posts/index.tsx
  src/components/pages/home/index.tsx
  src/components/pages/home/trending-posts/ComingSoonAlert.tsx
  src/components/pages/home/trending-posts/TopRanking.tsx
  src/components/pages/home/trending-posts/index.tsx
  src/components/svg-component/BellSvg.tsx
  tailwind.config.js
Labels: ✍️ UI

#28 [DEV-14] feat: 단어장 페이지 좋아요 목록 필터링 기능 추가
  src/app/user/wordbook/page.tsx
  src/components/pages/wordbook/WordbookDropdown.tsx
  src/components/pages/wordbook/index.tsx
  src/constants/sortingOptions.ts
  src/fetcher/index.ts
  src/hooks/query/useGetLikedWord.ts
  src/hooks/useDropdown.ts
Labels: ✨ feat

#34 hotfix: middleware cookie setting
  src/middleware.ts
Labels: 🐛 bug

#35 [DEV-72] wordDetail API 및 URL 를 id => name 방식으로 변경
  src/app/api/auth/kakao/redirect/route.ts
  src/app/word/search/page.tsx
  src/app/words/[wordName]/loading.tsx
  src/app/words/[wordName]/page.tsx
  src/components/common/WordItem.tsx
  src/components/pages/wordbook/index.tsx
  src/routes/path.ts
Labels: ✨ feat

#38 hotfix: url 수정
  src/app/api/auth/kakao/redirect/route.ts
Labels: 🐛 bug

#36 [DEV-35] 페이지별 메타데이터, og태그 추가
  public/dev-malssami.png
  public/vite.svg
  src/app/apple-icon.png
  src/app/icon.ico
  src/app/layout.tsx
  src/app/opengraph-image.png
  src/app/quiz/page.tsx
  src/app/user/wordbook/page.tsx
  src/app/word/search/PageClient.tsx
  src/app/word/search/page.tsx
  src/app/words/[wordName]/page.tsx
  src/hooks/useOptimisticLike.ts
Labels: ✨ feat

#37 [DEV-15] 메인 페이지 좋아요 API 연동
  src/actions/index.ts
  src/components/common/WordItem.tsx
  src/components/pages/home/all-posts/index.tsx
  src/components/pages/home/index.tsx
  src/components/pages/wordbook/index.tsx
  src/types/main.ts
Labels: 🐛 bug, ✨ feat

#41 [DEV-76] hotfix: 메타데이터 빌드 에러나는 부분 수정
  src/app/layout.tsx
  src/app/user/wordbook/page.tsx
  src/app/word/search/page.tsx
Labels: 🐛 bug

#42 [DEV-80] hotfix: 빌드 에러 수정
  src/app/user/wordbook/page.tsx
  src/app/word/search/page.tsx
  src/components/pages/wordbook/index.tsx
Labels: 🐛 bug

#43 fix: public폴더가 현재 없기 때문에 임시로 주석 처리
  Dockerfile
Labels: 🐛 bug

#45 [DEV-64] 메인 페이지 관련 기능 전체 픽스
  src/app/api/auth/kakao/redirect/route.ts
  src/app/home/page.tsx
  src/components/common/LoginAlertModal.tsx
  src/components/common/WordItem.tsx
  src/components/pages/home/all-posts/index.tsx
  src/components/pages/home/index.tsx
  src/fetcher/index.ts
  src/fetcher/types.ts
  src/hooks/query/useGetAllPosts.ts
  src/hooks/useSyncURLWithState.ts
  src/routes/path.ts
Labels: ♻️ refactor

#44 [DEV-67]: Detail Page UI 수정 반영
  src/actions/index.ts
  src/app/words/[wordName]/page.tsx
  src/components/pages/detail/DetailHeader.tsx
  src/components/pages/detail/LikeButton.tsx
  src/components/pages/detail/PronunciationDetail.tsx
  src/components/svg-component/DetailPronunciationCloseArrowSvg.tsx
  src/components/svg-component/DetailPronunciationCorrectSvg.tsx
  src/components/svg-component/DetailPronunciationShowArrowSvg.tsx
  src/components/svg-component/DetailPronunciationWrongSvg.tsx
  src/hooks/mutation/useAddLike.ts
  src/hooks/mutation/useDeleteLike.ts
  src/hooks/useOptimisticLike.ts
Labels: ✨ feat

#46 [DEV-64] fix: 메인 페이지 좋아요시 리렌더링 이슈 해결
  package-lock.json
  package.json
  src/app/layout.tsx
  src/components/common/WordItem.tsx
  src/components/pages/home/all-posts/index.tsx
  src/constants/queryKey.ts
  src/fetcher/index.ts
  src/hooks/query/ useAuthQuery.ts
  src/hooks/useMutationLike.ts
Labels: ♻️ refactor

#50 fix: build error 임시 수정
  src/components/pages/wordbook/index.tsx
Labels: 🐛 bug

#47 [DEV-85] style: 로그인 페이지 디자인 QA 반영
  src/components/pages/login/index.tsx
Labels: ✍️ UI

#48 fix: 디테일 페이지 디자인 QA 반영 (디테일 배경 제외)
  src/app/words/[wordName]/page.tsx
  src/components/common/CopiedNotice.tsx
  src/components/pages/detail/DetailHeader.tsx
  src/components/pages/detail/PronunciationDetail.tsx
  tailwind.config.js
Labels: ✍️ UI

#49 [DEV-83] style: 메인 페이지 디자인 QA 반영
  src/app/global.css
  src/components/common/Pagination.tsx
  src/components/common/WordItem.tsx
  src/components/layout/Header.tsx
  src/components/layout/SearchBar.tsx
  src/components/pages/home/HomeToggleZone.tsx
  src/components/pages/home/trending-posts/ComingSoonAlert.tsx
  src/components/pages/home/trending-posts/TrendingDescription.tsx
  src/components/svg-component/HamburgerMenuSvg.tsx
Labels: ✍️ UI

#51 feat: 비로그인 시 로그인 토스트 UI 로직 추가
  src/actions/index.ts
  src/components/pages/detail/LikeButton.tsx
  src/hooks/useOptimisticLike.ts
Labels: ✨ feat

#54 fix: build typo 파일명 error 수정
  src/components/pages/detail/LikeButton.tsx
Labels: 🐛 bug

#55 [DEV-88] 검색 자동완성 기능 추가
  src/app/word/search/PageClient.tsx
  src/app/word/search/page.tsx
  src/components/common/ToolTip.tsx
  src/components/layout/Header.tsx
  src/components/layout/SearchBar.tsx
  src/components/pages/search/AutoComplete.tsx
  src/components/pages/search/EngNotice.tsx
  src/components/pages/search/SearchItem.tsx
  src/components/pages/search/index.tsx
  src/components/svg-component/HamburgerMenuSvg.tsx
  src/components/svg-component/MagnifierSvg.tsx
  src/components/svg-component/NoWordSvg.tsx
  src/components/svg-component/WarningBellSvg.tsx
  src/fetcher/index.ts
  src/fetcher/types.ts
  src/hooks/query/useGetSearchWord.ts
  src/hooks/useMutationLike.ts
  src/types/main.ts
Labels: ✨ feat

#40 [DEV-33] 마이 페이지, 회원탈퇴 페이지 구현
  next.config.mjs
  src/app/home/page.tsx
  src/app/profile/DeleteAccount/page.tsx
  src/app/profile/Non-login/page.tsx
  src/app/profile/[id]/page.tsx
  src/components/layout/Header.tsx
  src/components/pages/detail/ReportButton.tsx
  src/components/pages/profile/DeleteAccount.tsx
  src/components/pages/profile/Modal/DeleteAccountModal.tsx
  src/components/pages/profile/Modal/LogoutModal.tsx
  src/components/pages/profile/NonLoginProfileInfo.tsx
  src/components/pages/profile/ProfileHeader.tsx
  src/components/pages/profile/ProfileInfo.tsx
  src/components/pages/profile/SubmitFeedback.tsx
  src/components/pages/profile/index.tsx
  src/components/svg-component/BigEmailSvg.tsx
  src/components/svg-component/EmailSvg.tsx
  src/components/svg-component/NonLoginImage.tsx
  src/components/svg-component/PowerSvg.tsx
  src/components/svg-component/QuizSvg.tsx
  src/components/svg-component/RightAngleBracketSvg.tsx
  src/components/svg-component/SubmitFeedbackSvg.tsx
  src/components/svg-component/WordBookSvg.tsx
  src/fetcher/index.ts
  src/fetcher/types.ts
  src/routes/path.ts
Labels: ✨ feat

#56 fix: design QA 반영 - header, 좋아요 하트 정렬
  src/components/pages/detail/DetailHeader.tsx
  src/components/pages/detail/LikeButton.tsx
  src/components/pages/search/SearchItem.tsx
  src/components/svg-component/DetailLikeActiveSvg.tsx
  src/components/svg-component/DetailLikeSvg.tsx
Labels: 🐛 bug, ✍️ UI

#58 fix: 자동완성 build error 수정
  src/components/layout/SearchBar.tsx
  src/components/pages/search/AutoComplete.tsx
  src/components/pages/search/SearchItem.tsx
Labels: 🐛 bug

#61 feat: quiz page 개발
  package-lock.json
  package.json
  src/app/quiz/@modal/page.tsx
  src/app/quiz/page.tsx
  src/app/quiz/result/[quizResultId]/@modal/(.)share/page.tsx
  src/app/quiz/result/[quizResultId]/@modal/default.tsx
  src/app/quiz/result/[quizResultId]/@modal/page.tsx
  src/app/quiz/result/[quizResultId]/layout.tsx
  src/app/quiz/result/[quizResultId]/page.tsx
  src/app/quiz/result/[quizResultId]/share/page.tsx
  src/app/words/[wordName]/page.tsx
  src/components/common/ShareModal.tsx
  src/components/pages/quiz/GuestQuizResult.tsx
  src/components/pages/quiz/QuizPlay.tsx
  src/components/pages/quiz/QuizResult.tsx
  src/components/pages/quiz/QuizResultDetail.tsx
  src/components/pages/quiz/QuizResultDetailWord.tsx
  src/components/pages/quiz/QuizScore.tsx
  src/components/pages/quiz/index.tsx
  src/components/pages/quiz/quizData.ts
  src/components/svg-component/CloseSvg1.tsx
  src/components/svg-component/KakaoShareSvg.tsx
  src/components/svg-component/LinkShareSvg.tsx
  src/components/svg-component/ShareButtonSvg.tsx
  src/constants/queryKey.ts
  src/fetcher/backendFetch.ts
  src/fetcher/index.ts
  src/fetcher/serverFetch.ts
  src/fetcher/types.ts
  src/hooks/mutation/useQuizResult.ts
  src/hooks/query/useGetQuizData.ts
  src/routes/path.ts
  src/store/index.ts
Labels: ✨ feat

#62 [DEV-83] 메인페이지 수정사항 전체 반영
  src/app/global.css
  src/components/common/LoginAlertModal.tsx
  src/components/layout/SearchBar.tsx
  src/components/pages/home/HomeToggleZone.tsx
  src/components/pages/home/all-posts/index.tsx
  src/components/pages/home/trending-posts/ComingSoonAlert.tsx
  src/components/svg-component/NoWordSvg.tsx
  src/fetcher/index.ts
Labels: ♻️ refactor

#57 [DEV-87] fix: 좋아요 버튼 클릭 시 단어장 페이지에 바로 반영되지 않고 새로고침해야 반영되는 문제 해결
  src/hooks/useMutationLike.ts
Labels: 🐛 bug

#60 [DEV-98] 단어장 페이지에 비로그인 상태로 진입하면 로그인 페이지로 redirect하도록 처리
  src/app/layout.tsx
  src/middleware.ts
  src/utils/index.ts
Labels: ✨ feat

#64 [DEV-103] 검색바 수정
  src/components/layout/SearchBar.tsx
  src/fetcher/index.ts
Labels: 🐛 bug

#66 [DEV-99]fix: 디테일 페이지 컴마 띄어쓰기 수정
  src/components/pages/detail/PronunciationDetail.tsx
Labels: 🐛 bug, ✍️ UI

#72 [DEV-110] 카카오 공유하기 수정 외
  .github/workflows/production.yml
  src/components/common/WordItem.tsx
  src/hooks/useLoadKakaoScript.ts
Labels: 🐛 bug

#71 feat: 로그인 페이지 진입 시 로그인된 유저면 home으로 redirect
  src/app/home/page.tsx
  src/fetcher/index.ts
  src/fetcher/server.ts
  src/middleware.ts
Labels: 🐛 bug, ✨ feat

#68 fix: 마이페이지 수정 버튼 변경
  src/components/pages/profile/ProfileInfo.tsx
  src/components/pages/profile/index.tsx
Labels: 🐛 bug

#70 [DEV-111] 회원 탈퇴 시 의견 보내도록 변경
  src/components/pages/profile/DeleteAccount.tsx
  src/components/pages/profile/Modal/DeleteAccountModal.tsx
Labels: 🐛 bug

#74 [DEV-104] 비로그인 상태에서 로그아웃, 회원탈퇴 안보이도록 수정, 단어장 페이지 접근 시 토스트 추가
  src/app/profile/Non-login/page.tsx
  src/app/profile/[id]/page.tsx
  src/components/pages/profile/index.tsx
Labels: 🐛 bug

#73 fix: 단어장 페이지 디자인 QA 반영
  src/components/pages/wordbook/WordbookDropdown.tsx
  src/components/pages/wordbook/index.tsx
Labels: 🐛 bug

#76 fix: 프로필 이미지 안나오는 문제 nextConfig 수정으로 해결, fallback UI 생성
  next.config.mjs
  src/app/api/auth/kakao/redirect/route.ts
  src/components/pages/profile/ProfileInfo.tsx
  src/components/svg-component/DefaultProfileIconSvg.tsx
Labels: 🐛 bug, ✨ feat

#77 [DEV-116]fix: quiz 디테일이 모바일에서 짤리는 문제 해결
  src/components/pages/quiz/QuizResultDetail.tsx
  src/middleware.ts
Labels: 🐛 bug

#82 fix: 빌드 에러 수정
  src/components/pages/detail/ReportButton.tsx
Labels: 🐛 bug

#85 [DEV-121] fix: quiz 결과 누적 수정(atom 초기화)
  src/components/pages/quiz/index.tsx
Labels: 🐛 bug

#84 [DEV-120] 로그아웃, 회원탈퇴 이후 단어장으로 접근 가능했던 문제 수정
  src/components/pages/profile/Modal/DeleteAccountModal.tsx
  src/components/pages/profile/Modal/LogoutModal.tsx
Labels: 🐛 bug

#87 fix: 폰트 굵기 smoothing 적용
  src/app/layout.tsx
Labels: 🐛 bug

#88 [DEV-124] 단어 검색에 debounce 적용 및 SearchBar 컴포넌트 리팩터링
  src/app/word/search/page.tsx
  src/components/layout/Header.tsx
  src/components/layout/SearchBar.tsx
  src/components/pages/search/AutoComplete.tsx
  src/components/pages/search/EngNotice.tsx
  src/hooks/useDebounce.ts
  src/hooks/useOnClickOutside.ts
Labels: ✨ feat, ♻️ refactor

#93 [DEV-130] 트렌딩 단어 순위 API 연동 및 컴포넌트 수정
  src/app/home/page.tsx
  src/components/pages/home/trending-posts/GeneralRanking.tsx
  src/components/pages/home/trending-posts/RankChange.tsx
  src/components/pages/home/trending-posts/TopRanking.tsx
  src/components/pages/home/trending-posts/index.tsx
  src/components/svg-component/FillArrowSvg.tsx
  src/components/svg-component/HyphenSvg.tsx
  src/constants/queryKey.ts
  src/fetcher/server.ts
  src/fetcher/types.ts
  src/hooks/query/useGetTrendList.ts
Labels: ✨ feat

#91 fix: 검색 페이지 -> 마이 페이지 이동 시 비로그인 마이페이지로 이동하는 문제 수정
  src/app/word/search/page.tsx
Labels: 🐛 bug

#90 fix: 퀴즈 페이지 내 헤더 텍스트를 개발 용어 발음 퀴즈로 수정
  src/components/layout/SearchBar.tsx
  src/components/pages/quiz/QuizPlay.tsx
Labels: 🐛 bug

#92 fix: no-cache to no-store
  src/fetcher/backendFetch.ts
  src/fetcher/serverFetch.ts
Labels: 🐛 bug

#86 fix: 모바일 브라우저에서 로그인 페이지 스크롤이 생기는 문제 수정
  src/app/global.css
  src/app/layout.tsx
  src/components/layout/HeightWrapper.tsx
  src/components/pages/login/index.tsx
  src/utils/index.ts
Labels: 🐛 bug

#89 [DEV-123] 메인 페이지 스켈레톤 UI 적용
  src/app/home/page.tsx
  src/app/layout.tsx
  src/components/common/WordItem.tsx
  src/components/pages/home/HomeSkeleton.tsx
Labels: ✨ feat, ✍️ UI

#96 fix: 검색, 자동완성 기능 수정
  src/components/layout/SearchBar.tsx
  src/components/pages/search/AutoComplete.tsx
  src/components/pages/search/EngOnlyAlert.tsx
Labels: ✨ feat

#98 [DEV-143] 단어 검색 및 상세 정보 열람 페이지에 URL Encoding 적용
  src/app/word/search/page.tsx
  src/app/words/[wordName]/page.tsx
  src/components/layout/SearchBar.tsx
  src/routes/path.ts
Labels: 🐛 bug

#97 fix: URL 공유 모달 뜰 때, 한번 더 클릭 시 없어지도록 변경
  src/components/common/CopiedNotice.tsx
  src/components/common/ShareModal.tsx
  src/components/pages/detail/URLShareButton.tsx
  src/hooks/useCopyClipboard.ts
Labels: ✨ feat

#94 fix: 마이 페이지 url 변경
  src/app/home/page.tsx
  src/app/profile/Non-login/page.tsx
  src/app/profile/page.tsx
  src/app/word/search/page.tsx
  src/components/layout/Header.tsx
  src/components/pages/profile/Modal/DeleteAccountModal.tsx
  src/components/pages/profile/Modal/LogoutModal.tsx
  src/components/pages/profile/index.tsx
  src/routes/path.ts
Labels: ✨ feat
