Repository Devminjeong-eum/frontend, pull requests merged in 2024-07, with the labels that each got.

#100 [DEV-156] 트렌딩 단어 페이지에서 순위 아이템 클릭시 바로 디테일 페이지로 이동되도록 수정
  src/components/pages/home/index.tsx
  src/components/pages/home/trending-posts/GeneralRanking.tsx
  src/components/pages/home/trending-posts/TopRanking.tsx
Labels: ♻️ refactor

#101 [DEV-157] 모든 용어 보기 기본 노출 아이템 개수 수정
  src/app/home/page.tsx
  src/components/pages/home/HomeSkeleton.tsx
  src/components/pages/home/all-posts/index.tsx
  src/components/pages/home/index.tsx
  src/components/pages/home/trending-posts/index.tsx
  src/components/pages/search/index.tsx
  src/constants/home.constants.ts
  src/fetcher/index.ts
  src/fetcher/server.ts
  src/hooks/useLoadKakaoScript.ts
  src/types/main.ts
Labels: ♻️ refactor

#103 [DEV-132] 퀴즈 페이지 QA 반영
  src/components/pages/quiz/QuizPlay.tsx
  src/components/pages/quiz/QuizResult.tsx
  src/components/pages/quiz/QuizResultDetail.tsx
  src/components/pages/quiz/QuizResultDetailWord.tsx
  src/components/pages/quiz/QuizScore.tsx
  src/components/pages/quiz/index.tsx
  src/components/svg-component/DefaultProfileIconSvg.tsx
  src/components/svg-component/HyphenSvg.tsx
  src/components/svg-component/ScoreResultSvg.tsx
  src/components/svg-component/ScoreSvg.tsx
Labels: ♻️ refactor

#102 fix: quiz refetch 설정, staleTIme, gcTime 설정 및 퀴즈 데이터 revalidate 처리
  src/components/pages/quiz/index.tsx
  src/hooks/query/useGetQuizData.ts
Labels: 🐛 bug

#104 [DEV-160] 마이 페이지 QA 반영
  src/app/profile/delete/page.tsx
  src/components/pages/profile/DeleteAccount.tsx
  src/components/pages/profile/Modal/DeleteAccountModal.tsx
  src/components/pages/profile/Modal/InquiryModal.tsx
  src/components/pages/profile/Modal/LogoutModal.tsx
  src/components/pages/profile/NonLoginProfileInfo.tsx
  src/components/pages/profile/ProfileHeader.tsx
  src/components/pages/profile/SubmitFeedback.tsx
  src/components/pages/profile/index.tsx
  src/components/pages/quiz/QuizPlay.tsx
  src/components/svg-component/NonLoginImage.tsx
  src/routes/path.ts
Labels: ♻️ refactor

#106 feat: 디테일 페이지 QA 반영, 안내문구 삽입
  src/app/words/[wordName]/page.tsx
  src/components/pages/detail/PronunciationDetail.tsx
  src/components/svg-component/DetailKoreanAlertIconSvg.tsx
Labels: 🐛 bug, ✍️ UI

#105 feat: PWA 적용
  Dockerfile
  next.config.mjs
  package-lock.json
  package.json
  public/icon-192x192.png
  public/icon-256x256.png
  public/icon-384x384.png
  public/icon-512x512.png
  public/sw.js
  public/sw.js.map
  public/workbox-e43f5367.js
  public/workbox-e43f5367.js.map
  src/app/manifest.ts
Labels: ✨ feat

#107 [DEV-162] 단어장 페이지 QA 사항 반영
  src/components/pages/wordbook/QuizBanner.tsx
  src/components/pages/wordbook/index.tsx
Labels: 🐛 bug

#108 [DEV-134] 복사완료화면이 오른쪽으로 밀리지 않도록 수정
  src/components/common/CopiedNotice.tsx
Labels: 🐛 bug

#109 [DEV-168] 메인 로고 클릭시 트렌딩 페이지로 이동되도록 수정
  public/sw.js.map
  src/components/pages/home/index.tsx
  src/hooks/useSyncURLHomeRouteState.ts
  src/hooks/useSyncURLWithState.ts
Labels: 🐛 bug

#112 [DEV-175] 퀴즈 결과 페이지 공유 기능 툴팁 UI 추가
  public/sw.js.map
  src/app/word/search/page.tsx
  src/components/layout/Header.tsx
  src/components/layout/SearchBar.tsx
  src/components/pages/home/QuizButton.tsx
  src/components/pages/quiz/QuizResult.tsx
  src/components/pages/quiz/QuizShareTooltip.tsx
  src/components/pages/search/AutoComplete.tsx
  src/components/pages/search/NotFoundWord.tsx
Labels: ✨ feat

#115 [DEV-155] TTS 기능 구현, 메인 페이지 UI 수정 및 유저 디바이스 체크기능 추가
  public/sw.js.map
  src/components/common/TTSPlayer.tsx
  src/components/common/WordItem.tsx
  src/components/pages/home/HomeSkeleton.tsx
  src/components/pages/home/index.tsx
  src/components/svg-component/SpeakerSvg.tsx
  src/constants/queryKey.ts
  src/fetcher/index.ts
  src/hooks/query/useGetTTSUrl.ts
  src/hooks/useAudioPlayer.ts
  src/hooks/useDeviceType.ts
Labels: ✨ feat, ✍️ UI

#113 [DEV-165] 다양한 크기의 favicon파일 추가, 애플 터치 아이콘 파일 교체
  public/icon-16x16.ico
  public/icon_144x144.png
  public/icon_48x48.png
  public/icon_96x96.png
  public/sw.js.map
  src/app/apple-icon.png
  src/app/layout.tsx
Labels: ✨ feat

#114 [DEV-164] 단어 추가 폼 버튼 UI 구현
  public/sw.js.map
  src/components/pages/detail/ReportButton.tsx
  src/components/pages/profile/Modal/InquiryModal.tsx
  src/components/pages/profile/index.tsx
  src/components/pages/quiz/QuizPlay.tsx
  src/components/pages/search/AutoComplete.tsx
  src/components/pages/search/NotFoundWord.tsx
  src/components/pages/wordbook/WordbookHeader.tsx
  src/components/pages/wordbook/index.tsx
  src/components/svg-component/RightAngleBracketSvg.tsx
  src/routes/path.ts
Labels: ✨ feat
